<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Sort All Clients</name>
   <tag></tag>
   <elementGuidId>eb1461f8-9a04-41d6-a6f6-75c8b4e341f5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.mat-mdc-tab-body-content.ng-tns-c2396234108-295.ng-trigger.ng-trigger-translateTab > div.search-filter-block.document-content-header.gap-12.px-3.py-2.ng-star-inserted > button.mat-mdc-menu-trigger.button-text.mdc-button.mat-mdc-button.mat-unthemed.mat-mdc-button-base > span.mdc-button__label > img[alt=&quot;icon&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//img[@ngsrc='/assets/images/ui-uplift-icons/global/sort-Icon.svg'])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;All Clients&quot;i >> internal:attr=[title=&quot;Sort Docs&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>53228e21-6d00-4e40-80e7-92c6cf610c50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ngsrc</name>
      <type>Main</type>
      <value>/assets/images/ui-uplift-icons/global/sort-Icon.svg</value>
      <webElementGuid>3f1811e9-a660-4d0f-bfb3-71bd2ebf3c36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>icon</value>
      <webElementGuid>0c078e02-9f54-4f27-85d1-f6f358412026</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>1848a726-aa0c-4d7e-a9ef-13a9738237e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>18</value>
      <webElementGuid>1f768ddb-73a3-4488-9e1e-6da28d8b53d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>40beac32-643c-4412-9810-d717e6a996e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fetchpriority</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>3da38ece-543c-4310-ab38-732410e29c4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-img</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>3a17d08c-7ea3-4f5e-9dfd-43a0906f9616</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/assets/images/ui-uplift-icons/global/sort-Icon.svg</value>
      <webElementGuid>89c43c08-c420-4c6d-8312-9eaa990a1d2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-tab-content-4-1&quot;)/div[@class=&quot;mat-mdc-tab-body-content ng-tns-c2396234108-295 ng-trigger ng-trigger-translateTab&quot;]/div[@class=&quot;search-filter-block document-content-header gap-12 px-3 py-2 ng-star-inserted&quot;]/button[@class=&quot;mat-mdc-menu-trigger button-text mdc-button mat-mdc-button mat-unthemed mat-mdc-button-base&quot;]/span[@class=&quot;mdc-button__label&quot;]/img[1]</value>
      <webElementGuid>804ce7fa-9df8-45a4-84df-882295700e04</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-tab-body[@id='mat-tab-content-4-1']/div/div/button[2]/span[2]/img</value>
      <webElementGuid>b71cd01e-f1d8-4086-945f-1486667177c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='icon'])[430]</value>
      <webElementGuid>0743d648-c9fa-4821-b220-35db760101e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-tab-body[2]/div/div/button[2]/span[2]/img</value>
      <webElementGuid>b1902277-be00-4c4c-b3f6-79071c3eaea3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'icon' and @src = '/assets/images/ui-uplift-icons/global/sort-Icon.svg']</value>
      <webElementGuid>b1d4f263-025f-420e-a86e-a8fb4b02dd45</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
