<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>TC05 drop word file 01</name>
   <tag></tag>
   <elementGuidId>f431364d-07f3-4189-9531-51edcba9b593</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@title = 'TB-4-AUWODC.docx' and (text() = 'TB-4-AUWODC.docx' or . = 'TB-4-AUWODC.docx')]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>7e57f0ac-659a-406b-b8fb-4df550792437</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cdk-drag list-item-content</value>
      <webElementGuid>9fdae2e0-2ba6-4833-b7fc-ac80f4e1903d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>TB-3-AUWODC.docx</value>
      <webElementGuid>d293d9ee-29ee-4e3b-9b13-71c985e1df98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>TB-3-AUWODC.docx</value>
      <webElementGuid>afc59dc4-277b-45a8-9d0c-efc4bb39eed2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tbDoc-TB-3-AUWODC.docx&quot;)/div[@class=&quot;cdk-drag list-item-content&quot;]</value>
      <webElementGuid>a48eedef-82e7-4ec3-8768-331e8c8b508a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='tbDoc-TB-3-AUWODC.docx']/div</value>
      <webElementGuid>301eb7fc-0a77-4fab-b844-6cdd0a13d919</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TB-2-5576.txt'])[1]/following::div[2]</value>
      <webElementGuid>fe3eface-407f-4abe-bd3b-19d83d0dbd54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TB-1-02 Rename Via Automation .csv'])[1]/following::div[4]</value>
      <webElementGuid>818a226a-5563-4dfe-9aaa-8902258fccb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TB-4-AUEXDC.csv'])[1]/preceding::div[2]</value>
      <webElementGuid>9aa4602b-2963-4ade-a5f6-da755cc78d26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/div</value>
      <webElementGuid>9cf1fd70-5b9f-4e61-8b15-61021c91585f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@title = 'TB-3-AUWODC.docx' and (text() = 'TB-3-AUWODC.docx' or . = 'TB-3-AUWODC.docx')]</value>
      <webElementGuid>3822290a-712b-4a2f-95b9-184fbd90e718</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
