<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Sort All Clients (1)</name>
   <tag></tag>
   <elementGuidId>92a026f9-32e9-47b5-a12a-f066162f2f39</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.mat-mdc-tab-body-content.ng-tns-c2396234108-295.ng-trigger.ng-trigger-translateTab > div.search-filter-block.document-content-header.gap-12.px-3.py-2.ng-star-inserted > button.mat-mdc-menu-trigger.button-text.mdc-button.mat-mdc-button.mat-unthemed.mat-mdc-button-base > span.mdc-button__label > img[alt=&quot;icon&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//img[@ngsrc='/assets/images/ui-uplift-icons/global/sort-Icon.svg'])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;All Clients&quot;i >> internal:attr=[title=&quot;Sort Docs&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>220e12ae-5b48-4b52-a05e-0df079efa77d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ngsrc</name>
      <type>Main</type>
      <value>/assets/images/ui-uplift-icons/global/sort-Icon.svg</value>
      <webElementGuid>f3e79635-f64a-4370-ad3f-d5efe91c726b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>icon</value>
      <webElementGuid>2c88f83d-4bb0-4b59-a9ff-8c57b2fa5035</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>346a3af1-d67b-41bd-bf5a-71f3d984d306</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>18</value>
      <webElementGuid>449a8ed9-d328-44a4-abae-6ff2699aa478</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>7855d38f-0888-48c3-8d75-63b89b60044d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fetchpriority</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>fe14457e-e23b-4556-9af7-78793346384b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-img</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>2f0e6470-4262-4304-b573-ab06e8612275</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/assets/images/ui-uplift-icons/global/sort-Icon.svg</value>
      <webElementGuid>ab561e70-1617-4db3-8bb5-f954c151c95e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-tab-content-4-1&quot;)/div[@class=&quot;mat-mdc-tab-body-content ng-tns-c2396234108-295 ng-trigger ng-trigger-translateTab&quot;]/div[@class=&quot;search-filter-block document-content-header gap-12 px-3 py-2 ng-star-inserted&quot;]/button[@class=&quot;mat-mdc-menu-trigger button-text mdc-button mat-mdc-button mat-unthemed mat-mdc-button-base&quot;]/span[@class=&quot;mdc-button__label&quot;]/img[1]</value>
      <webElementGuid>f380a1b5-8cfd-4e05-9bbb-a06331171be3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-tab-body[@id='mat-tab-content-4-1']/div/div/button[2]/span[2]/img</value>
      <webElementGuid>cba31bbc-d7ee-4e59-9de8-438d1e63224d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='icon'])[430]</value>
      <webElementGuid>cd4adf57-812f-4c03-b95a-6ad5e5e0f744</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-tab-body[2]/div/div/button[2]/span[2]/img</value>
      <webElementGuid>9a8cead3-757f-48f2-95c1-67488f138f1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'icon' and @src = '/assets/images/ui-uplift-icons/global/sort-Icon.svg']</value>
      <webElementGuid>1b87e32a-1dba-4ece-8294-7d6bf7cf50f2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
