<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Budgeted hours (H)_ng-star-inserted</name>
   <tag></tag>
   <elementGuidId>5c47412a-fce6-4bd6-8b2c-557795e895b9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@alt='done']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.ng-star-inserted</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;done&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>0c338812-14c3-4816-bed6-6330964ab1d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/assets/images/ui-uplift-icons/global/save-green.svg</value>
      <webElementGuid>b741f283-72d6-48c7-ab14-93338f408c38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>done</value>
      <webElementGuid>caffc271-6ab0-41cf-a2db-9944674fa60a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-star-inserted</value>
      <webElementGuid>adf56a97-6d30-4fe7-bafa-b37d683ccad8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/app-dashboard[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;dasboard-container layout-dashboard drawer-small&quot;]/div[@class=&quot;content-body&quot;]/div[@class=&quot;dashboard-main&quot;]/app-create-engagement[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;page-wraper client-engagement-info-wrapper right-side-panel-hide&quot;]/div[@class=&quot;content-block-main gap-20&quot;]/div[@class=&quot;client-engagement-info flexbox-column w-100&quot;]/div[@class=&quot;create-eng-outer flex-nowrap step2body&quot;]/div[@class=&quot;e-right-main pb-20&quot;]/div[@class=&quot;right-panel-eng mt-lg-0 mt-4&quot;]/div[@class=&quot;details-step2 ng-star-inserted&quot;]/div[@class=&quot;card&quot;]/div[@class=&quot;card-body p-0&quot;]/div[@class=&quot;table-responsive&quot;]/table[@class=&quot;mat-mdc-table mdc-data-table__table cdk-table table-countable row-height-auto font-inter row-editalbe&quot;]/tbody[@class=&quot;mdc-data-table__content&quot;]/tr[@class=&quot;mat-mdc-row mdc-data-table__row cdk-row ng-star-inserted&quot;]/td[@class=&quot;mat-mdc-cell mdc-data-table__cell cdk-cell cdk-column-actions mat-column-actions ng-star-inserted mat-mdc-table-sticky mat-mdc-table-sticky-border-elem-right&quot;]/div[@class=&quot;button-group gap-2 flex-nowrap justify-content-end ng-star-inserted&quot;]/button[@class=&quot;button-small-icon-action mdc-button mat-mdc-button mdc-button--unelevated mat-mdc-unelevated-button mat-secondary mat-mdc-button-base cdk-focused cdk-mouse-focused&quot;]/span[@class=&quot;mdc-button__label&quot;]/img[@class=&quot;ng-star-inserted&quot;]</value>
      <webElementGuid>569fdd28-7f54-4ecc-bb00-39bdc469e2f4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='done']</value>
      <webElementGuid>4925e6e7-9a07-43a8-8c3b-69c7dba41009</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[10]/div/button/span[2]/img</value>
      <webElementGuid>a5322177-7065-4d41-a2c8-d1905ee6291f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/assets/images/ui-uplift-icons/global/save-green.svg' and @alt = 'done']</value>
      <webElementGuid>2b1ed5f9-2fe9-48f4-a5a2-c5d3758122a2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
