<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>close search bar</name>
   <tag></tag>
   <elementGuidId>be9f3a03-d450-4829-989f-4f0293e00fd8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@title = 'Close']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.close-img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>1884f967-6778-4b14-a77c-88f5cce9fec9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Close</value>
      <webElementGuid>9ec34098-72ae-46fe-be51-3eea5a7f7f6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/assets/images/ui-uplift-icons/global/cross-red.svg</value>
      <webElementGuid>a3d8453e-ff9f-43fe-9691-bcb4161f1ed1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>icon</value>
      <webElementGuid>9e7af415-65e1-4f6a-8d65-bc098d899c2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>close-img</value>
      <webElementGuid>bd45be3b-7959-4b5a-9acc-2fd5a31aa8f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-tab-content-11-0&quot;)/div[@class=&quot;mat-mdc-tab-body-content ng-tns-c2396234108-1745 ng-trigger ng-trigger-translateTab&quot;]/div[@class=&quot;panel-right-content template-block-main overflow-hidden ng-star-inserted&quot;]/div[@class=&quot;collapsable-search-block-below p-2 ng-star-inserted expanded&quot;]/mat-form-field[@class=&quot;mat-mdc-form-field fixed-label label-none icon-form-left icon-form-right form-field-medium ng-tns-c1798928316-1744 mat-mdc-form-field-type-mat-input mat-mdc-form-field-label-always-float mat-mdc-form-field-has-icon-prefix mat-mdc-form-field-has-icon-suffix mat-form-field-appearance-fill mat-primary ng-star-inserted&quot;]/div[@class=&quot;mat-mdc-text-field-wrapper mdc-text-field ng-tns-c1798928316-1744 mdc-text-field--filled&quot;]/div[@class=&quot;mat-mdc-form-field-flex ng-tns-c1798928316-1744&quot;]/div[@class=&quot;mat-mdc-form-field-icon-suffix ng-tns-c1798928316-1744 ng-star-inserted&quot;]/button[@class=&quot;border-start mdc-button mat-mdc-button mat-unthemed mat-mdc-button-base ng-tns-c1798928316-1744&quot;]/span[@class=&quot;mdc-button__label&quot;]/img[@class=&quot;close-img&quot;]</value>
      <webElementGuid>7f71518e-8292-441b-a147-5c433406eaa7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-tab-body[@id='mat-tab-content-11-0']/div/div/div[3]/mat-form-field/div/div[2]/div[3]/button/span[2]/img</value>
      <webElementGuid>fd766ef1-f25c-4ff8-abe7-17b04435d042</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='icon'])[7]</value>
      <webElementGuid>a0212096-9f3b-4ba4-9395-009c0b2019c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button/span[2]/img</value>
      <webElementGuid>b83df058-0ef6-47e9-a5df-19e9ef6bb570</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@title = 'Close' and @src = '/assets/images/ui-uplift-icons/global/cross-red.svg' and @alt = 'icon']</value>
      <webElementGuid>e581bccf-aed2-4f0e-b146-ae3374778fe7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
