<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Prod Document Repo icon client via</name>
   <tag></tag>
   <elementGuidId>03ad713b-6a05-40c3-a76a-e9ac3d271781</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@src = '/assets/images/ui-uplift-icons/global/insert-drive-file-rightpanel.svg']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.ng-star-inserted</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>8f1e01f2-c47e-4f36-94c7-f0b157c8e41a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/assets/images/ui-uplift-icons/global/insert-drive-file-rightpanel.svg</value>
      <webElementGuid>38a1b3dc-9bff-489c-bfe3-f5b1f4a0f250</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-star-inserted</value>
      <webElementGuid>09d5b891-d9c5-42b7-89b3-62da121af8b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-tab-label-9-0&quot;)/span[@class=&quot;mdc-tab__content&quot;]/span[@class=&quot;mdc-tab__text-label&quot;]/img[@class=&quot;ng-star-inserted&quot;]</value>
      <webElementGuid>543c020d-6fa6-4b13-bcce-9a67292b58e5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mat-tab-label-9-0']/span[2]/span/img</value>
      <webElementGuid>d72510bd-dccf-41e8-b746-a21f49cf88a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/span/img</value>
      <webElementGuid>848a23b0-7bbc-4f6a-a5e0-1fa19bbc1160</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/assets/images/ui-uplift-icons/global/insert-drive-file-rightpanel.svg']</value>
      <webElementGuid>403ca116-4824-4fef-b26d-d578d5f43f5c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
