<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>search icon click</name>
   <tag></tag>
   <elementGuidId>ff7cb35e-601e-479d-b4e8-bc5d0976e079</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@title = 'Search' and @src = '/assets/images/ui-uplift-icons/global/search-Icon.svg' and @alt = 'icon']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.expand-img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>d04fc3f0-7e93-460e-ac01-f1337ba1fb5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>ef7b5c3e-4291-476d-a543-2533fb3662f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/assets/images/ui-uplift-icons/global/search-Icon.svg</value>
      <webElementGuid>52468b6c-a8a1-47b5-a89d-e2a2cd031b46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>icon</value>
      <webElementGuid>5a611f65-8cf0-49e7-9366-bd09655359c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>expand-img</value>
      <webElementGuid>11222c91-1f1b-4b3a-9641-99209085d851</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-tab-content-7-0&quot;)/div[@class=&quot;mat-mdc-tab-body-content ng-tns-c2396234108-702 ng-trigger ng-trigger-translateTab&quot;]/div[@class=&quot;panel-right-content template-block-main overflow-hidden ng-star-inserted&quot;]/div[@class=&quot;search-filter-block gap-12 px-3 py-2 ng-star-inserted&quot;]/button[@class=&quot;button-text search-toogle-button mdc-button mat-mdc-button mat-unthemed mat-mdc-button-base&quot;]/span[@class=&quot;mdc-button__label&quot;]/img[@class=&quot;expand-img&quot;]</value>
      <webElementGuid>c68a61b9-8635-45ff-b2ab-db563246c4d1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-tab-body[@id='mat-tab-content-7-0']/div/div/div[2]/button[5]/span[2]/img</value>
      <webElementGuid>9fe675f7-39c6-4f8c-9dde-134d0466e9d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='icon'])[5]</value>
      <webElementGuid>4740ab79-be21-4491-8acf-cc754933864b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[5]/span[2]/img</value>
      <webElementGuid>0d829a4c-3f4a-43b7-b766-4ef2d5334b5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@title = 'Search' and @src = '/assets/images/ui-uplift-icons/global/search-Icon.svg' and @alt = 'icon']</value>
      <webElementGuid>5352e431-f703-4300-b628-f56cfa4426e2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
